// import React from 'react'
import './globals.css';
import { Inter } from 'next/font/google';
import StyleComponentsRegistry from 'app/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleComponentsRegistry>{children}</StyleComponentsRegistry>
      </body>
    </html>
  );
}
