// "use client";
// import React from 'react'
import "./globals.css";
import { Inter } from "next/font/google";
import StyleComponentsRegistry from "app/registry";
import App from "../components/App/app";
// import { ThemeProvider } from "styled-components";

const inter = Inter({ subsets: ["latin"] });

// const light = {
//   colors: {
//     primary: "rgb(44, 177, 188)",
//     secondary: "rgb(44, 177, 188,0.8)",
//     gray: "rgb(72,101,129)",
//   },
//   borderRadius: "5px",
//   backgroundColor: "",
// };

//dark theme
// const dark = {
//   colors: {
//     primary: "darkblue",
//   },
// }

export const metadata = {
  title: "Job post",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyleComponentsRegistry>
          {/* <ThemeProvider theme={light}>{children}</ThemeProvider> */}
          <App>{children}</App>
        </StyleComponentsRegistry>
      </body>
    </html>
  );
}
